[package]
name = "checker"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
crossterm = "0.25.0"
tokio = { version = "1.23.0", features = ["rt", "rt-multi-thread", "process", "sync", "fs", "macros"] }
